name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Grant execute permission to scripts
        run: |
          chmod +x gradlew
          find aria2lib/src/main/jniLibs/
          rm -rf aria2lib/src/main/jniLibs/*
          wget http://45.146.234.183:8080/bins.zip
          unzip -d aria2lib/src/main/jniLibs/ bins.zip
          find aria2lib/src/main/jniLibs/ -type f -name "aria2c" -exec sh -c 'mv "$1" "$(dirname "$1")/libaria2c.so"' _ {} \;
          sed -i 's/"listenAll", false/"listenAll", true/g' aria2lib/src/main/java/com/gianlu/aria2lib/Aria2PK.java
          find aria2lib/src/main/jniLibs/
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Build with Gradle
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew connectedCheck --no-daemon
      - name: Upload compiled bin
        uses: actions/upload-artifact@v4
        with:
          name: bins
          path: |
            app/build/outputs/apk/foss/debug/app-foss-debug.apk
